#include <iostream>
#include <fstream>
using namespace std;
unsigned int A[100000],B[100000];
unsigned int n,m;
bool same[100000];
void PTuChungPrint(unsigned int A[100000], unsigned int n, unsigned int B[100000], unsigned int m){
    for (unsigned int )
}
int main(){
    freopen("PTCHUNG.INP","r",stdin);
    freopen("PTUCHUNG.OUT","w",stdout);
    cin>>n>>m;
    for (unsigned int i=0; i<n; i++){
        cin>>A[i];
    }
    for (unsigned int j=0; j<m; j++){
        cin>>B[j];
    }
    PTuChungPrint(A,n,B,m);
}
